# -*- coding: utf-8 -*-
"""area of circle

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XAyZpfPB8VRZHVtvRUoSzxl8XzPyKACo
"""

print("calculatinga rea of a circle")
r=50
p=3.142
area=p*r*2
print("area is",area)

